# Generated by Django 3.1.1 on 2022-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='gender-none.png', null=True, upload_to=''),
        ),
    ]
